###
POST http://localhost:5000/todos
Content-Type: application/json

{
  "description": "[as]"
}

###
GET http://localhost:5000/todos

###
GET http://localhost:5000/todos/:id

###
PUT http://localhost:5000/todos/:id
Content-Type: application/json

{
  "description": "learn data analytics"
}

###
DELETE http://localhost:5000/todos/4
Content-Type: application/json

